# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-23 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilte', models.CharField(max_length=100, null=True)),
                ('evenement', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('picture', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
