# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-23 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(default=0, upload_to=b''),
            preserve_default=False,
        ),
    ]
