# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-23 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20200323_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='tilte',
            new_name='title',
        ),
    ]
