# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-23 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('timeline', '0003_auto_20200323_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLinePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='timeline_timelinepluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('text', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
