# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-23 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_timelinepluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinepluginmodel',
            name='events',
            field=models.ManyToManyField(to='timeline.Event'),
        ),
    ]
