# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-23 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('teamplugin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamListPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='teamplugin_teamlistpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('teams', models.ManyToManyField(to='teamplugin.TeamPluginModel')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
